name: TWRP Recovery Builder 2024 for VIT_T4310 (Android 5.1)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build TWRP for VIT_T4310
    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Check Out
      uses: actions/checkout@v4

    - name: Setup Build Environment
      run: |
        sudo apt update
        sudo apt install -y git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 x11proto-core-dev libx11-dev lib32ncurses5-dev lib32z1-dev ccache unzip libstdc++6 libncurses5 libtinfo5
        sudo apt install -y python2 python-is-python2
        sudo ln -sf /usr/bin/python2 /usr/bin/python

    - name: Install GCC 4.9
      run: |
        sudo apt install -y gcc-4.9 g++-4.9
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 100

    - name: Install OpenJDK 7
      run: |
        sudo apt install -y openjdk-7-jdk
        export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
        echo "export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64" >> $GITHUB_ENV
        echo "export PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

    - name: Install Repo
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Initialize Repo
      run: |
        mkdir -p ~/android_build/workspace
        cd ~/android_build/workspace
        repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-5.1

    - name: Sync Repo
      run: |
        cd ~/android_build/workspace
        repo sync -j$(nproc --all) --force-sync

    - name: Clone Device Tree
      run: |
        cd ~/android_build/workspace
        git clone https://github.com/Eduzul123/twrp_device_vit_VIT_T4310 -b twrp-5.1 device/vit/VIT_T4310

    - name: Setup Environment Variables
      run: |
        export ALLOW_MISSING_DEPENDENCIES=true
        echo "export ALLOW_MISSING_DEPENDENCIES=true" >> $GITHUB_ENV

    - name: Build Recovery
      run: |
        cd ~/android_build/workspace
        source build/envsetup.sh
        lunch omni_VIT_T4310-eng
        make clean
        make recoveryimage -j$(nproc --all)

    - name: Upload Recovery Image
      uses: actions/upload-artifact@v4
      with:
        name: recovery-image
        path: ~/android_build/workspace/out/target/product/VIT_T4310/recovery.img
