name: TWRP Recovery Build for VIT T4310

on:
  push:
    branches:
      - twrp-5.1
  pull_request:
    branches:
      - twrp-5.1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Limpieza con Slimhub
      uses: rokibhasansagar/slimhub_actions@main
      with:
        cleanup: true

    - name: Configurar Java 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Configurar Git
      run: |
        git config --global user.name "TuNombreDeUsuario"
        git config --global user.email "TuCorreo@example.com"

    - name: Clonar repositorio del 치rbol de dispositivo
      run: |
        mkdir -p device/vit/VIT_T4310
        git clone -b twrp-5.1 https://github.com/Eduzul123/twrp_device_vit_VIT_T4310.git device/vit/VIT_T4310

    - name: Instalar dependencias
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev

    - name: Instalar repo
      run: |
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
        chmod +x ~/repo
        sudo mv ~/repo /usr/local/bin/repo

    - name: Inicializar y sincronizar fuentes de TWRP
      run: |
        mkdir -p ~/twrp
        cd ~/twrp
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-5.1
        repo sync -j$(nproc --all) --force-sync

    - name: Configurar entorno de compilaci칩n
      run: |
        cd ~/twrp
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        lunch omni_VIT_T4310-eng

    - name: Compilar imagen de recuperaci칩n
      run: |
        cd ~/twrp
        mka recoveryimage

    - name: Subir artefacto de la imagen de recuperaci칩n
      uses: actions/upload-artifact@v4
      with:
        name: recovery.img
        path: ~/twrp/out/target/product/VIT_T4310/recovery.img
